query ($page: Int!, $perPage: Int!) {
    characters(
        paginate: { page: $page, perPage: $perPage }
    ) {
        ... on CharactersList {
            entries {
                id
                name
                episodes
            }
            maxPages
        }
    }
}
