query ($page: Int!, $perPage: Int!) {
    characters(
        paginate: { page: $page, perPage: $perPage }
    ) {
        ... on CharactersList {
            page
            perPage
            maxPages
        }
    }
}
