query ($page: Int!, $perPage: Int!) {
    characters(
        paginate: { page: $page, perPage: $perPage }
    ) {
        entries {
            id
            name
            episodes
        }
        page
        perPage
        maxPages
    }
}
