mutation ($name: String!, $episodes: [String!]!) {
    createCharacter(
        character: { name: $name, episodes: $episodes }
    ) {
        ... on Character {
            id
            name
            episodes
        }

        ... on CharacterAlreadyExistsError {
            code
        }
    }
}
